# Generated by Django 3.1.2 on 2021-07-08 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_auto_20210708_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(max_length=150)),
                ('policy_premium', models.FloatField()),
                ('policy_cover', models.FloatField()),
                ('policy_state', models.CharField(max_length=50)),
                ('policy_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
