# Generated by Django 3.1.2 on 2021-07-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_policy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Policy',
        ),
    ]
