# Generated by Django 3.1.2 on 2021-07-09 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_auto_20210708_0559'),
        ('customer_policy', '0002_delete_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('type', models.CharField(max_length=150)),
                ('premium', models.FloatField()),
                ('cover', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_status', models.CharField(max_length=50)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('policy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_policy.policy')),
            ],
        ),
    ]
